### ISSUE TITLE
Request - texto 2 voice

### ISSUE THREAD

**Issue by dudumaroja** [laysaalves/medgrandma-ai#1]
Achei incrivel sua ideia e aplicação, e votei nela.

Sugiro adicionar text to voice para complementar, ja que dificuldade de leitura é tambem um impecilio para idosos.

**Comment by laysaalves** [comment]
Valeu demais!!! Com certeza esse complemento vai entrar no projeto assim que eu terminar de subir as features que estou desenvolvendo agora :)))
